<a href="https://colab.research.google.com/github/panda-sai/Frozen-Lake-MDP-Q-Learning/blob/master/MDP_Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [0]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [0]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [0]:
rewards_all_episodes = []

In [0]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 
      exploration_rate_threshold = random.uniform(0, 1)
      
      if exploration_rate_threshold > exploration_rate:
          action = np.argmax(q_table[state,:]) 
      else:
          action = env.action_space.sample()

      new_state, reward, done, info = env.step(action)

      q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
      learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

      state = new_state
      rewards_current_episode += reward 

      if done == True: 
          break

    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

rewards_all_episodes.append(rewards_current_episode)


rewards_per_thosand_episodes = np.array_split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.0
2000 :  0
3000 :  0
4000 :  0
5000 :  0
6000 :  0
7000 :  0
8000 :  0
9000 :  0
10000 :  0


********Q-table********

[[0.52268351 0.47199181 0.47234859 0.47563403]
 [0.35073003 0.37317467 0.26942546 0.49219355]
 [0.42429882 0.42133148 0.3993117  0.44933672]
 [0.32695072 0.27763493 0.27472008 0.42564689]
 [0.53707741 0.27345441 0.42655116 0.42059241]
 [0.         0.         0.         0.        ]
 [0.34791409 0.15895519 0.14882198 0.1114073 ]
 [0.         0.         0.         0.        ]
 [0.36685078 0.34492494 0.37836126 0.57883491]
 [0.50608878 0.6276847  0.51287487 0.43674296]
 [0.55969084 0.37780814 0.41679647 0.32423429]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46579737 0.54948529 0.75372079 0.64648256]
 [0.72174012 0.89275124 0.75252814 0.77487332]
 [0.         0.         0.         0.        ]]


In [0]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break            
            
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
